---
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: componentA
  description: a component
  tags:
  - springboot
spec:
  owner: groupA
  lifecycle: "production"
  system: systemA
  dependsOn: []
  consumesApis: []
  type: "service"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: componentA-api
  description: the API
spec:
  system: systemA
  type: openapi
  lifecycle: production
  owner: groupA
  apiProvidedBy: component:componentA # this does not work
  definition: |
    some thing here
